#!/bin/bash
# Change this to appropriate class path!
dir=../out/production/INF558_Project/

MODE="encode"
while getopts "d" opt; do
  case $opt in
    d)
      MODE="decode"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

shift $((OPTIND-1))

if [ $# -ne 2 ]
  then
    echo "Usage: hiroZip [-d] <infile> <outfile>"
    exit 1
fi

mkdir hiroZipTemp
if [ "$MODE" == "encode" ]
then
  echo "encoding..."
  java -classpath $dir bw.BWTransformer $1 > hiroZipTemp/BW
  java -classpath $dir m2f.M2FCoder hiroZipTemp/BW > hiroZipTemp/MTF
  java -classpath $dir adaptive_huffman.HuffmanCoder hiroZipTemp/MTF $2
else
  echo "decoding..."
  java -classpath $dir adaptive_huffman.HuffmanDecoder $1 hiroZipTemp/M2F
  java -classpath $dir m2f.M2FDecoder hiroZipTemp/M2F > hiroZipTemp/BW
  java -classpath $dir bw.BWDetransformer hiroZipTemp/BW > $2
fi
rm -rf hiroZipTemp
