#!/bin/bash
# Change this to appropriate class path!
dir=../out/production/AdaptiveBurrowsWheeler/

MODE="encode"
while getopts "d" opt; do
  case $opt in
    d)
      MODE="decode"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

shift $((OPTIND-1))

if [ $# -ne 2 ]
  then
    echo "Usage: hiroZip [-d] <infile> <outfile>"
    exit 1
fi

mkdir hiroZipTemp
if [ "$MODE" == "encode" ]
then
  echo "encoding..."
  java -classpath $dir bw.BWTransformer $1 > hiroZipTemp/BW
  java -classpath $dir m2f.M2FEncoder hiroZipTemp/BW > hiroZipTemp/M2F
  java -classpath $dir rle.RunLengthEncoder hiroZipTemp/M2F hiroZipTemp/RLE
  java -classpath $dir adaptive_huffman.HuffmanEncoder hiroZipTemp/RLE $2
else
  echo "decoding..."
  java -classpath $dir adaptive_huffman.HuffmanDecoder $1 hiroZipTemp/RLE2
  java -classpath $dir rle.RunLengthDecoder hiroZipTemp/RLE2 hiroZipTemp/M2F2
  java -classpath $dir m2f.M2FDecoder hiroZipTemp/M2F2 > hiroZipTemp/BW2
  java -classpath $dir bw.BWDetransformer hiroZipTemp/BW2 > $2
fi
#rm -rf hiroZipTemp
